### ISSUE TITLE
Files cannot be added

### ISSUE THREAD

**Issue by mvaudel** [proteomexchange/px-submission-tool#23]
Hello,

When attempting to attach raw files the tool complains that our files cannot be attached because empty. The files are accessible to the tool as directly generated by the instrument and not empty.

Any hint on how to get unstuck?

Thank you!

Marc

![pride](https://cloud.githubusercontent.com/assets/11632644/11118074/71b8b584-893f-11e5-9784-bf4a4a661c5f.png)

**Comment by Tobias-Ternent** [comment]
Sorry for the late reply in this, but did you manage to resolve this issue on your own?

I think what may have been the problem is. Is your G:\ drive a shared drive over your network? Your computer's Java might have problems reading files contained on network drives, especially if they're quite large. I know of a few users who had experienced a similar thing - they got over this by copying the files manually to the computer's hard drive locally, and using those files directly instead, then everything was fine.

**Comment by mvaudel** [comment]
Hi Tobias,

No worries, Attila has helped me on this one and we sent the data via ftp :) The problem was that the files were in fact folders. Would it be an idea for the tool to estimate the size of the content in such cases?

Best regards,

Marc

**Comment by mvaudel** [comment]
Hi Tobias,

Did you by any chance have the time to look into this?

Best regards,

Marc

**Comment by Tobias-Ternent** [comment]
Hi @mvaudel,

We've not been able to schedule any time to look into issues with the tool yet. Hopefully later on this year we will, but I can't give you an estimation about when that would be happening.

I agree though, it would be best to give perhaps a status/progress bar showing that the tool is still working to add files, how many files, and a total size.

**Comment by mvaudel** [comment]
Great, thank you!

**Comment by sureshhewabi** [comment]
A file size column added to the add file section, so that user can identify if the file is empty or not by file size
